name: Simple CD - Hunter

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout do c√≥digo
        uses: actions/checkout@v3

      - name: Verificar Docker j√° instalado
        run: docker --version

      - name: Build da imagem Docker
        run: docker build -t hunter-app .

      - name: Deploy (simulado)
        run: echo "Deploy realizado com sucesso! A imagem hunter-app foi constru√≠da."

      - name: Finaliza√ß√£o
        run: echo "üéâ CD executado com sucesso!"
